vault_redmine_db_database = c9qhnlesaas1go8lnss9
vault_redmine_db_username = user_test
vault_redmine_db_password = hexlet135
vault_redmine_db_port = 3000

vault_datadog_api_key = 09288b7284183bdce1113dd73d6fe65e
